### ISSUE TITLE
No module named _pywrap_tensorflow

### ISSUE THREAD

**Issue by JimSEOW** [shishaochen/TensorFlow-0.8-Win#1]
keras:: No module named _pywrap_tensorflow
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
tensorflow:: No module named _pywrap_tensorflow

**Comment by shishaochen** [comment]
Sorry, I don't know what you mean.
_py_tensorflow is the name of DLL what the C++ part of TensorFlow codes produces.
Anyway, please use latest CMAKE and Visual Studio 2015 and build this project.

**Comment by JimSEOW** [comment]
I have cloned the master and built according to CMAKE 2 days ago with GPU support and it works!
